version: "3.9"

x-spark-common: &spark-common
  env_file:
    - docker-compose.spark.env
  networks:
    datalake_net:

services:
  master:
    <<: *spark-common
    build: .
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master", "-h", "master"]
    container_name: spark-master
    environment:
      MASTER: spark://master:7077
      SPARK_DRIVER_CORES: 1
      SPARK_DRIVER_MEMORY: 4g
    ports:
      # - 7077:7077
      - 8080:8080
      - 4040:4040
    depends_on:
      - minio

  worker:
    <<: *spark-common
    build: .
    command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.worker.Worker", "spark://master:7077"]
    environment:
      SPARK_WORKER_CORES: 2
      SPARK_WORKER_MEMORY: 8g
    ports:
      - 8081:8081
    depends_on:
      - master

  minio:
    image: minio/minio:RELEASE.2022-05-26T05-48-41Z # If upgrading tag, see https://stackoverflow.com/a/73047454/22623325
    command: ["server", "/data", "--console-address", ":9001"]
    env_file:
      - docker-compose.minio.env
    environment:
      MINIO_DOMAIN: minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ./data:/data
    networks:
      datalake_net:
        aliases:
          - warehouse.minio

networks:
  datalake_net:
